// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmxizlromjuehblihfpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpteGl6bHJvbWp1ZWhibGloZnBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTgzMzQsImV4cCI6MjA2Mzc3NDMzNH0.vCUr-EzndJEQZn6ItgU2ofMoN4KYo2N3gHj02fyNw0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);